### ISSUE TITLE
Attempting to follow tutorial with this repo and running into issues..

### ISSUE THREAD

**Issue by Guyverix** [pradesn/fashion-store-slim4#1]
I have the database all created + data-filled from the SQL file, and confirmed access, however with a clean composer install I get errors right off the bat for routing..

```
[Thu Sep  7 18:44:10 2023] 192.168.15.58:51260 [404]: GET /
[Thu Sep  7 18:44:10 2023] 192.168.15.58:51260 Closing
[Thu Sep  7 18:44:12 2023] 192.168.15.58:51270 Accepted
[Thu Sep  7 18:44:12 2023] 404 Not Found
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /opt/nmsApi05/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 76
Trace: #0 /opt/nmsApi05/vendor/slim/slim/Slim/Routing/RouteRunner.php(56): Slim\Middleware\RoutingMiddleware->performRouting()
#1 /opt/nmsApi05/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Slim\Routing\RouteRunner->handle()
#2 /opt/nmsApi05/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#3 /opt/nmsApi05/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#4 /opt/nmsApi05/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#5 /opt/nmsApi05/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#6 /opt/nmsApi05/public/index.php(222): Slim\App->run()
#7 {main}
[Thu Sep  7 18:44:12 2023] 192.168.15.58:51270 [404]: GET /
[Thu Sep  7 18:44:12 2023] 192.168.15.58:51270 Closing
```

I have no idea what I messed up, I have tested this against nginx, apache, and straight PHP using php -S 192.168.15.66:9080 -t public

I am quite certain the cause is my lack of knowledge, but am not sure how to continue troubleshooting this.

In both Postman and my browser, I am attempting: http://192.168.15.66:9080/

**Comment by Guyverix** [comment]
[composer.txt](https://github.com/pradesn/fashion-store-slim4/files/12552542/composer.txt)

Attached is my composer lock file.  I did not see one from your example, so assume that whatever composer installs will be compatible by default..

**Comment by pradesn** [comment]
@Guyverix remove the backslash (/) in the end of the setbasePath in index.php
example:
`$app->setBasePath('/fashion-store-slim4/public');`

**Comment by Guyverix** [comment]
Thank you for getting back to me.  No luck, there was not a backslash present in the setBasePath..  I will keep poking at this and see what the heck I messed up.  
```
$app = AppFactory::create();
//$app->setBasePath('/fashion-store-slim4/public');
//$app->setBasePath('/public');
$app->setBasePath('/nmsApi05/public');
$app->addErrorMiddleware(true, true, true);
```

**Comment by pradesn** [comment]
@Guyverix clone it first then use this setting 
- composer.lock
[composer.txt](https://github.com/pradesn/fashion-store-slim4/files/12759788/composer.txt)
- postman collection
[Fashion-Store-Slim4.postman_collection.txt](https://github.com/pradesn/fashion-store-slim4/files/12759916/Fashion-Store-Slim4.postman_collection.txt)

I run this on ubuntu 20.04, php7.4

**Comment by Guyverix** [comment]
Got it!  I will download and attempt after I install PHP 7.4..  I have been attempting this on PHP 8.2
Thank you very much!
